server:
  port: 8762
#  context-path: /member
eureka:
  client:
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: member
#redis 配置信息
  redis:
    host: 127.0.0.1
    password:
    port: 6379
    pool:
      max-idle: 100
      min-idle: 1
      max-active: 1000
      max-wait: -1
#数据库连接信息
  datasource:
        url: jdbc:mysql://127.0.0.1:3306/it-member?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false
        username: root
        password: 123456
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml # mybatis配置文件所在路径
  type-aliases-package: com.it.entity  # 所有Entity别名类所在包
  mapper-locations:
    - classpath:mybatis/mapper/**/*.xml # mapper映射文件
